
FIRST_SURCHARGE_AFTER_DAY = 10
SECOND_SURCHARGE_AFTER_DAY = 15
FIRST_SURCHARGE_PERCENT = 10
SECOND_SURCHARGE_PERCENT = 15
FAMILY_DISCOUNT_PERCENT = 5
TEACHER_DISCOUNT_PERCENT = 50
THREE_FOUR_KLASSES_DISCOUNT_PERCENT = 5
FIVE_OR_MORE_KLASSES_DISCOUNT_PERCENT = 10
DEBIT_EXTRA_CENTS = 500000 # $5000,00
DEBIT_EXTRA = Money.new(DEBIT_EXTRA_CENTS, 'ARS')