# This is an autogenerated file for dynamic methods in Installment
# Please rerun rake rails_rbi:models[Installment] to regenerate.

# typed: strong
module Installment::EnumInstanceMethods
  extend T::Sig

  sig { returns(T::Boolean) }
  def january?; end

  sig { void }
  def january!; end

  sig { returns(T::Boolean) }
  def february?; end

  sig { void }
  def february!; end

  sig { returns(T::Boolean) }
  def march?; end

  sig { void }
  def march!; end

  sig { returns(T::Boolean) }
  def april?; end

  sig { void }
  def april!; end

  sig { returns(T::Boolean) }
  def may?; end

  sig { void }
  def may!; end

  sig { returns(T::Boolean) }
  def june?; end

  sig { void }
  def june!; end

  sig { returns(T::Boolean) }
  def july?; end

  sig { void }
  def july!; end

  sig { returns(T::Boolean) }
  def august?; end

  sig { void }
  def august!; end

  sig { returns(T::Boolean) }
  def september?; end

  sig { void }
  def september!; end

  sig { returns(T::Boolean) }
  def october?; end

  sig { void }
  def october!; end

  sig { returns(T::Boolean) }
  def november?; end

  sig { void }
  def november!; end

  sig { returns(T::Boolean) }
  def december?; end

  sig { void }
  def december!; end

  sig { returns(T::Boolean) }
  def waiting?; end

  sig { void }
  def waiting!; end

  sig { returns(T::Boolean) }
  def paid?; end

  sig { void }
  def paid!; end

  sig { returns(T::Boolean) }
  def paid_with_interests?; end

  sig { void }
  def paid_with_interests!; end
end

module Installment::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Installment::GeneratedAttributeMethods
  extend T::Sig

  sig { returns(Integer) }
  def amount_cents; end

  sig { params(value: T.any(Integer, Float, ActiveSupport::Duration)).void }
  def amount_cents=(value); end

  sig { returns(T::Boolean) }
  def amount_cents?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def created_at; end

  sig { params(value: T.any(DateTime, Date, Time, ActiveSupport::TimeWithZone)).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(T.nilable(BigDecimal)) }
  def hours; end

  sig { params(value: T.nilable(BigDecimal)).void }
  def hours=(value); end

  sig { returns(T::Boolean) }
  def hours?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: T.any(Integer, Float, ActiveSupport::Duration)).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(T.nilable(Integer)) }
  def membership_id; end

  sig { params(value: T.nilable(T.any(Integer, Float, ActiveSupport::Duration))).void }
  def membership_id=(value); end

  sig { returns(T::Boolean) }
  def membership_id?; end

  sig { returns(T.nilable(String)) }
  def month; end

  sig { params(value: T.nilable(T.any(Integer, String, Symbol))).void }
  def month=(value); end

  sig { returns(T::Boolean) }
  def month?; end

  sig { returns(T.nilable(String)) }
  def status; end

  sig { params(value: T.nilable(T.any(Integer, String, Symbol))).void }
  def status=(value); end

  sig { returns(T::Boolean) }
  def status?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def updated_at; end

  sig { params(value: T.any(DateTime, Date, Time, ActiveSupport::TimeWithZone)).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end

  sig { returns(T.nilable(Integer)) }
  def year; end

  sig { params(value: T.nilable(T.any(Integer, Float, ActiveSupport::Duration))).void }
  def year=(value); end

  sig { returns(T::Boolean) }
  def year?; end
end

module Installment::GeneratedAssociationMethods
  extend T::Sig

  sig { returns(::Klass::ActiveRecord_Associations_CollectionProxy) }
  def klasses; end

  sig { params(value: T::Enumerable[::Klass]).void }
  def klasses=(value); end

  sig { returns(::Membership) }
  def membership; end

  sig { params(value: ::Membership).void }
  def membership=(value); end

  sig { returns(::MoneyTransaction::ActiveRecord_Associations_CollectionProxy) }
  def payments; end

  sig { params(value: T::Enumerable[::MoneyTransaction]).void }
  def payments=(value); end

  sig { returns(T.nilable(::Person)) }
  def person; end

  sig { params(value: T.nilable(::Person)).void }
  def person=(value); end
end

module Installment::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Installment]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Installment]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Installment]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Installment)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Installment) }
  def find_by_id!(id); end
end

class Installment < ApplicationRecord
  include Installment::EnumInstanceMethods
  include Installment::GeneratedAttributeMethods
  include Installment::GeneratedAssociationMethods
  extend Installment::CustomFinderMethods
  extend T::Sig
  extend T::Generic

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def self.months; end

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def self.statuses; end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.not_waiting(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.waiting(*args); end

  sig { returns(Installment::ActiveRecord_Relation) }
  def self.all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_Relation) }
  def self.unscoped(&block); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.select(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.reselect(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.order(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.reorder(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.group(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.limit(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.offset(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.left_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.where(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.rewhere(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.preload(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.extract_associated(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.eager_load(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.includes(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.from(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.lock(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.readonly(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.or(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.having(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.create_with(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.distinct(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.references(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.none(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.unscope(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.merge(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.except(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def self.only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_Relation) }
  def self.extending(*args, &block); end

  sig { params(args: T.untyped).returns(Installment) }
  def self.find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Installment)) }
  def self.find_by(*args); end

  sig { params(args: T.untyped).returns(Installment) }
  def self.find_by!(*args); end

  sig { returns(T.nilable(Installment)) }
  def self.first; end

  sig { returns(Installment) }
  def self.first!; end

  sig { returns(T.nilable(Installment)) }
  def self.second; end

  sig { returns(Installment) }
  def self.second!; end

  sig { returns(T.nilable(Installment)) }
  def self.third; end

  sig { returns(Installment) }
  def self.third!; end

  sig { returns(T.nilable(Installment)) }
  def self.third_to_last; end

  sig { returns(Installment) }
  def self.third_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def self.second_to_last; end

  sig { returns(Installment) }
  def self.second_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def self.last; end

  sig { returns(Installment) }
  def self.last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def self.exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.one?(*args); end

  sig { params(attributes: T.untyped, block: T.untyped).returns(Installment) }
  def self.create(attributes = nil, &block); end

  sig { params(attributes: T.untyped, block: T.untyped).returns(Installment) }
  def self.create!(attributes = nil, &block); end

  sig { params(attributes: T.untyped, block: T.untyped).returns(Installment) }
  def self.new(attributes = nil, &block); end
end

class Installment::ActiveRecord_Relation < ActiveRecord::Relation
  include Installment::ActiveRelation_WhereNot
  include Installment::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Installment)

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def not_waiting(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def waiting(*args); end

  sig { returns(Installment::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_Relation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_Relation) }
  def extending(*args, &block); end
end

class Installment::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Installment::ActiveRelation_WhereNot
  include Installment::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Installment)

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_waiting(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def waiting(*args); end

  sig { returns(Installment::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped).returns(Installment) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Installment)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Installment) }
  def find_by!(*args); end

  sig { returns(T.nilable(Installment)) }
  def first; end

  sig { returns(Installment) }
  def first!; end

  sig { returns(T.nilable(Installment)) }
  def second; end

  sig { returns(Installment) }
  def second!; end

  sig { returns(T.nilable(Installment)) }
  def third; end

  sig { returns(Installment) }
  def third!; end

  sig { returns(T.nilable(Installment)) }
  def third_to_last; end

  sig { returns(Installment) }
  def third_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def second_to_last; end

  sig { returns(Installment) }
  def second_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def last; end

  sig { returns(Installment) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { override.params(block: T.proc.params(e: Installment).void).returns(T::Array[Installment]) }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Installment]) }
  def flatten(level); end

  sig { returns(T::Array[Installment]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end
end

class Installment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Installment::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Installment)

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_april(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_august(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_december(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_february(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_january(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_july(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_june(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_march(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_may(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def not_waiting(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def november(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def october(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def paid(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def paid_with_interests(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def september(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def waiting(*args); end

  sig { returns(Installment::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Installment::ActiveRecord_AssociationRelation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Installment::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped).returns(Installment) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Installment)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Installment) }
  def find_by!(*args); end

  sig { returns(T.nilable(Installment)) }
  def first; end

  sig { returns(Installment) }
  def first!; end

  sig { returns(T.nilable(Installment)) }
  def second; end

  sig { returns(Installment) }
  def second!; end

  sig { returns(T.nilable(Installment)) }
  def third; end

  sig { returns(Installment) }
  def third!; end

  sig { returns(T.nilable(Installment)) }
  def third_to_last; end

  sig { returns(Installment) }
  def third_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def second_to_last; end

  sig { returns(Installment) }
  def second_to_last!; end

  sig { returns(T.nilable(Installment)) }
  def last; end

  sig { returns(Installment) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { override.params(block: T.proc.params(e: Installment).void).returns(T::Array[Installment]) }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Installment]) }
  def flatten(level); end

  sig { returns(T::Array[Installment]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end

  sig { params(records: T.any(Installment, T::Array[Installment])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Installment, T::Array[Installment])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Installment, T::Array[Installment])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Installment, T::Array[Installment])).returns(T.self_type) }
  def concat(*records); end
end
